package com.lotaris.rox.annotations;

//import com.lotaris.rox.common.model.TestFlag;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation to enrich the information for a test. The information
 * added to the test methods are used to send the test results to
 * Rox.
 *
 * @author Laurent Prevost, laurent.prevost@lotaris.com
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface RoxableTest {
	/**
	 * Unique key that identifies a test in Rox. The key
	 * is generated by Rox and is unique across a Rox deployment.
	 */
	String key();

	/**
	 * Descriptive name to override the name of a test manually
	 */
	String name() default "";
	
	/**
	 * Category of test: Ex: unit, selenium or integration 
	 */
	String category() default "";
	
	/**
	 * Tags for a test
	 */
	String[] tags() default {};
	
	/**
	 * Tickets that refers to a ticketing system
	 */
	String[] tickets() default {};

	/**
	 * Test flag
	 */
	TestFlag[] flags() default TestFlag.SPECIAL_VALUE_NOT_USED;
}
